# Generated by Django 5.2.8 on 2026-01-12 12:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da categoria')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('icon', models.CharField(blank=True, help_text='Ícone da categoria (ex: fa-hammer)', max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem de exibição')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('cliente', 'Cliente'), ('empreendedor', 'Empreendedor')], default='cliente', help_text='Tipo de usuário na plataforma', max_length=15)),
                ('phone', models.CharField(blank=True, help_text='Número de telefone/WhatsApp', max_length=20, verbose_name='Telefone')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, help_text='Onde você está localizado', max_length=200, verbose_name='Localização')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'cliente'}, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Empreendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200, verbose_name='Nome do negócio')),
                ('description', models.TextField(help_text='Descreva o que seu negócio faz e como pode ajudar clientes', verbose_name='Descrição do negócio')),
                ('location', models.CharField(help_text='Bairro, cidade ou zona onde atua', max_length=200, verbose_name='Localização')),
                ('whatsapp', models.CharField(help_text='Número para contato direto', max_length=20, verbose_name='WhatsApp')),
                ('price_range', models.CharField(blank=True, help_text='Ex: A partir de 500 MT, Entre 1000-5000 MT, Sob consulta', max_length=100, verbose_name='Faixa de preço')),
                ('services', models.TextField(help_text='Liste os principais serviços ou produtos (um por linha)', verbose_name='Serviços oferecidos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Perfil ativo')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verificado')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empreendedores', to='marketplace.category', verbose_name='Categoria principal')),
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'empreendedor'}, on_delete=django.db.models.deletion.CASCADE, related_name='empreendedor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empreendedor',
                'verbose_name_plural': 'Empreendedores',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('visualizado', 'Visualizado'), ('em_conversa', 'Em Conversa'), ('proposta_enviada', 'Proposta Enviada'), ('aceito', 'Aceito'), ('recusado', 'Recusado'), ('fechado', 'Fechado')], default='novo', max_length=20, verbose_name='Status')),
                ('message', models.TextField(blank=True, help_text='Mensagem personalizada do empreendedor para o cliente', verbose_name='Mensagem')),
                ('price_quote', models.DecimalField(blank=True, decimal_places=2, help_text='Orçamento proposto pelo empreendedor', max_digits=10, null=True, verbose_name='Orçamento (MT)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('empreendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='marketplace.empreendedor', verbose_name='Empreendedor')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lida')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de envio')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='marketplace.match', verbose_name='Match')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Mensagem',
                'verbose_name_plural': 'Mensagens',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='Necessidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Ex: Preciso de um eletricista urgente', max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Descreva detalhadamente o que você precisa', verbose_name='Descrição')),
                ('location', models.CharField(help_text='Onde o serviço deve ser realizado', max_length=200, verbose_name='Localização')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Quanto você pretende gastar (opcional)', max_digits=10, null=True, verbose_name='Orçamento (MT)')),
                ('urgency', models.CharField(choices=[('baixa', 'Baixa'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Urgência')),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('em_conversa', 'Em Conversa'), ('fechado', 'Fechado'), ('cancelado', 'Cancelado')], default='aberto', max_length=15, verbose_name='Status')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='necessidades', to='marketplace.category', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='necessidades', to='marketplace.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Necessidade',
                'verbose_name_plural': 'Necessidades',
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='match',
            name='necessidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='marketplace.necessidade', verbose_name='Necessidade'),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('necessidade', 'empreendedor')},
        ),
    ]
